title: Ankit
email: your@email.com
description: My personal website
baseurl: ""
url: "https://ankkit33.github.io"

theme: jekyll-theme-yat

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - portfolio.md
  - contact.md
